# Generated by Django 5.0.7 on 2024-07-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retreat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Signature', 'Signature')], max_length=50)),
                ('condition', models.CharField(choices=[('Stress Relief', 'Stress Relief')], max_length=50)),
                ('image', models.URLField()),
                ('tag', models.JSONField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
